#tomcat¶Ë¿Ú
server:
 port: 8082
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/jpa_study?serverTimezone=UTC
  username: root
  password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fd.springboot.entity
